### ISSUE TITLE
clone

### ISSUE THREAD

**Issue by web900621** [ionic-team/ionic-starter-super#133] opened 2017-09-21 00:56 UTC
ionic serve will get this error！

```
Runtime Error
Uncaught (in promise): Error: Cannot find module '../pages/tutorial/tutorial.module'. Error: Cannot find module '../pages/tutorial/tutorial.module'. at http://localhost:8100/build/main.js:27:9 at t.invoke (http://localhost:8100/build/polyfills.js:3:9283) at Object.onInvoke (http://localhost:8100/build/vendor.js:4508:37) at t.invoke (http://localhost:8100/build/polyfills.js:3:9223) at r.run (http://localhost:8100/build/polyfills.js:3:4452) at http://localhost:8100/build/polyfills.js:3:14076 at t.invokeTask (http://localhost:8100/build/polyfills.js:3:9967) at Object.onInvokeTask (http://localhost:8100/build/vendor.js:4499:37) at t.invokeTask (http://localhost:8100/build/polyfills.js:3:9888) at r.runTask (http://localhost:8100/build/polyfills.js:3:5143)
```

**Comment by danielsogl** [comment] 2017-09-21 04:35
I will take a look!

**Comment by shiftonetothree** [comment] 2017-10-04 09:24
@web900621 may be because you are using cnpm, switch to npm to reinstall,it may be allright

**Comment by danielsogl** [comment] 2017-10-04 09:44
I close this issue because I cant reproduce your error.

**Closed by danielsogl** 2017-10-04 09:44 UTC
