### ISSUE TITLE
Check if source is cordova after platform.ready()

### ISSUE THREAD

**Issue by simonhaenisch** [ionic-team/ionic-starter-super#137] opened 2017-10-06 10:48 UTC
related to #136 

After `platform.ready()`, if I don't check that the source is cordova, some native modules (like [OneSignal](http://ionicframework.com/docs/native/onesignal/)) throw errors in the browser that cordova is not available. Only tested that with `ionic cordova run android` so far, hope it's the correct way of doing it?

```ts
this.platform.ready().then(source => {
  if (source === 'cordova') {
    // now platform is ready and cordova is available => native modules can be used
    this.statusBar.styleDefault();
    this.splashScreen.hide();
  }
});
```

**Comment by janpio** [comment] 2017-10-06 11:24
My guess (and feeling): These errors are pretty much intended behaviour to make it clear that Ionic Native functionality is not available in the browser.

**Comment by danielsogl** [comment] 2017-10-06 11:27
@simonhaenisch I close this issue because it has nothing to do with the super-starter project itself.
All Ionic Native plugins without browser support throw this warning.

**Closed by danielsogl** 2017-10-06 11:27 UTC

**Comment by simonhaenisch** [comment] 2017-10-08 21:04
Why does it not have anything to do with the super-starter? Isn't this supposed to be a best practices starting point? And isn't that the way to handle native plugins without browser support?
